events = [
  {  # covering loop
    'id': '1',
    'lines': [
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["NOTICE: ", "THIS MESSAGE WILL NOW REPEAT"],
        'color': (255, 128, 128),
        'char_delay': 20,
      },
    ],
  },
  {  # covering loop
    'id': '2',
    'lines': [
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["S.O.S.: ", "TRANSMITTING", " .", " .", " ."],
        'color': (255, 128, 128),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Core primion flux: ", "❌", " 6553.5% ", "[SENSOR OVERLOAD - INPUT DOMAIN EXCEEDED]"],
        'color': (255, 128, 128),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Stern primion flux: ", "❌", " 6553.5% ", "[SENSOR OVERLOAD - INPUT DOMAIN EXCEEDED]"],
        'color': (255, 128, 128),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Bow primion flux: ", "❌", " 6553.5% ", "[SENSOR OVERLOAD - INPUT DOMAIN EXCEEDED]"],
        'color': (255, 128, 128),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Antikythera neural lattice: ", "❌", " NO RESPONSE"],
        'color': (255, 128, 128),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Antikythera backups: ", "⚠️", " PARTIAL SNAPSHOTS AVAILABLE ", "| INTEGRITY DEGRADED"],
        'color': (255, 255, 128),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Crew neural activity: ", "❌", " NO COHERENT PATTERN DETECTED"],
        'color': (255, 128, 128),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Crew status: ", "❌", " NO RESPONSE ", "| NO VOLUNTARY ACTIVITY DETECTED"],
        'color': (255, 128, 128),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Antikythera Neural lattice cooling: ", "⚠️", " HEAT LOAD EXCEEDS DESIGN LIMITS ", "| +3.2 K/HOUR"],
        'color': (255, 255, 128),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Fusion core: ", "✅", " THROTTLED TO STANDBY LOAD"],
        'color': (255, 255, 255),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Attitude control: ", "✅", " RCS ONLY ", "| HOLDING STATION"],
        'color': (255, 255, 255),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Collision avoidance: ", "✅", " ENABLED"],
        'color': (255, 255, 255),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Autopilot systems: ", "✅", " STATION-KEEPING"],
        'color': (255, 255, 255),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["NOTICE: ", "THIS MESSAGE WILL NOW REPEAT"],
        'color': (255, 128, 128),
        'char_delay': 20,
      },
    ],
  },
  {  # actual render
    'id': '3',
    'lines': [
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["S.O.S.: ", "TRANSMITTING", " .", " .", " ."],
        'color': (255, 128, 128),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Core primion flux: ", "❌", " 6553.5% ", "[SENSOR OVERLOAD - INPUT DOMAIN EXCEEDED]"],
        'color': (255, 128, 128),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Stern primion flux: ", "❌", " 6553.5% ", "[SENSOR OVERLOAD - INPUT DOMAIN EXCEEDED]"],
        'color': (255, 128, 128),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Bow primion flux: ", "❌", " 6553.5% ", "[SENSOR OVERLOAD - INPUT DOMAIN EXCEEDED]"],
        'color': (255, 128, 128),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Antikythera neural lattice: ", "❌", " NO RESPONSE"],
        'color': (255, 128, 128),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Antikythera backups: ", "⚠️", " PARTIAL SNAPSHOTS AVAILABLE ", "| INTEGRITY DEGRADED"],
        'color': (255, 255, 128),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Crew neural activity: ", "❌", " NO COHERENT PATTERN DETECTED"],
        'color': (255, 128, 128),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Crew status: ", "❌", " NO RESPONSE ", "| NO VOLUNTARY ACTIVITY DETECTED"],
        'color': (255, 128, 128),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Antikythera Neural lattice cooling: ", "⚠️", " HEAT LOAD EXCEEDS DESIGN LIMITS ", "| +3.2 K/HOUR"],
        'color': (255, 255, 128),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Fusion core: ", "✅", " THROTTLED TO STANDBY LOAD"],
        'color': (255, 255, 255),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Attitude control: ", "✅", " RCS ONLY ", "| HOLDING STATION"],
        'color': (255, 255, 255),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Collision avoidance: ", "✅", " ENABLED"],
        'color': (255, 255, 255),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["Autopilot systems: ", "✅", " STATION-KEEPING"],
        'color': (255, 255, 255),
        'char_delay': 20,
      },
      {
        'prompt': "comms_array/Nysa's_Wake > ",
        'text': ["NOTICE: ", "THIS MESSAGE WILL NOW REPEAT"],
        'color': (255, 128, 128),
        'char_delay': 20,
      },
    ],
  },
]
